### ISSUE TITLE
ENH: add F30 index

### ISSUE THREAD

**Issue by aburrell** [pysat/pysatSpaceWeather#119]
# Description
F30 is a solar index that has been show to correlate well to solar cycle changes in foF2.  The F30 is the Solar Flux measured by the Nobeyama Radio Observatory, which performs daily measurements of the 30 cm radio flux on an operational 7/365 basis.  However, the Nobeyama Radio Observatory is no longer operational.  There may be other sources of this index, but a historical data set is available.

## Potential impact

- Is the feature related to an existing problem? No
- How critical is this feature to your workflow? Not critical
- How wide of an impact to you anticipate this enhancement having?  Improving solar irradiance studies
- Would this break any existing functionality? No

## Potential solution(s)
Add data from: https://solar.nro.nao.ac.jp/norp/index.html

# Alternatives
Identify other sources of the index

# Additional context
Learned about this during EGU 2023.

https://www.swsc-journal.org/articles/swsc/pdf/2017/01/swsc160042.pdf
https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2022SW003359

**Comment by sespinoza08** [comment]
I am currently working on this feature. Due to the structure of the files from NoRP, I am thinking of just adding a NoRP instrument. It would be able to gather either calibrated data and/or fits data that spans over all frequencies available. Luckily, provided on the NoRP site is a Python library that contains reading routines and a summary plotter. 

The question - how should I go about adding the reading routines to my fork with proper acknowledgement? I don't see a readily available license on the code or the site.

## Example code (optional)
There are some functions such as 
```
norp_fits.norp_rd_1GHzI(fname)
norp_fits.norp_rd_1GHzCalD(fname)
norp_fits.norp_plot_summary(fname)
```
that are able to parse the binary files for raw data, calibrated data, and create summary plots from the day file.

## Configuration
 - OS : MacOS 12.0.1
 - Versions: 
     - Python 3.9.0
     - pysat 3.1.0

**Comment by aburrell** [comment]
Thanks for working on this @sespinoza08.  You don't have to add acknowledgements for dependent libraries, note all the packages that use numpy (for example) without an acknowledgement statement.  The `init` method in the instrument sub-module will need acknowledgements and references for the data, that will likely refer back to NoRP and either use their boiler-plate acknowledgement statement from their data usage page or something similar. 

I hope that answers your question, but it's possible I misunderstood. If you'd like to go over your work with me at any point prior to the pull request, let me know and we can set up a video call or something.
