### ISSUE TITLE
BUG: Instrument failure for `test_load_with_pad`

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysatSpaceWeather#127]
# Description
Several instruments fail when running against new tests in pysat develop. These include:
- [ ] sw_ap, tag='recent'
- [ ] sw_f107, tag='daily'
- [ ] sw_flare, tag='daily'
- [ ] sw_kp, tag='recent'
- [ ] sw_polarcap, tag='prediction'
- [ ] sw_sbfield, tag='daily'
- [ ] sw_ssn, tag='daily'

# To Reproduce this bug:
run pytest with pysat develop

## Test configuration
 - OS: Monterrey
 - Version python 3.10.9
 - pysat develop

# Additional context
polarcap has an `AssertionError` -- returned data is empty

All other returning a `KeyError` from deep within pandas

**Comment by aburrell** [comment]
The key error is a problems in the pysat padding implementation, which assumes that all columns will have a name.  There are some of these data sets, though, that will return an empty dataset object after padding, due to a difference in the loaded data and the way pysat handles slicing after padding.  I am preparing a pysat pull request to fix this.
